version: "3"
services:
  db:
      image: mysql:latest
      container_name: db
      restart: always
      ports:
        - 3306:3306
      environment:
        TZ: Asia/Jakarta 
        MYSQL_ROOT_PASSWORD: password
        MYSQL_USER: user
        MYSQL_PASSWORD: password
      volumes:
        - ./DB:/var/lib/mysql #copy db ke local 
      command: ["mysqld", "--default-time-zone=+07:00"] #ubah time zone db ke jkt

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      TZ: Asia/Jakarta 
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: password
      PMA_ARBITRARY: 1
  
  redis:
      image: redis:latest
      container_name: redis
      restart: always
      ports:
        - "6379:6379"
      command: redis-server /usr/local/etc/redis/redis.conf
      volumes:
        - ./redis/data:/data  # Lokasi penyimpanan data Redis di lokal
        - ./redis/redis.conf:/usr/local/etc/redis/redis.conf #setting configuration untuk redis di file redis.conf 
        
