version: "3"
services:
  laravel:
    tty: true
    container_name: laravel
    restart: always
    build:
      context: .
      dockerfile: /home/asa/Project/service/Laravel/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./Laravel/:/var/www/html

  golang: 
    tty: true
    container_name: golang
    restart: always
    build:
      context: .
      dockerfile: /home/asa/Project/service/Go/Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./Go/:/var/www/html

  db:
      image: mysql:latest
      container_name: db
      restart: always
      ports:
        - 3306:3306
      environment:
        TZ: Asia/Jakarta 
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: user
        MYSQL_PASSWORD: password
      volumes:
        - ./DB:/var/lib/mysql #copy db ke local 
      command: ["mysqld", "--default-time-zone=Asia/Jakarta"] #ubah time zone db ke jkt

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      TZ: Asia/Jakarta 
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
      PMA_ARBITRARY: 1
  
  redis:
      image: redis:latest
      container_name: redis
      restart: always
      ports:
        - "6379:6379"
      command: redis-server /usr/local/etc/redis/redis.conf
      volumes:
        - ./redis/data:/data  # Lokasi penyimpanan data Redis di lokal
        - ./redis/redis.conf:/usr/local/etc/redis/redis.conf #setting configuration untuk redis di file redis.conf 
        